language: node_js
node_js:
- lts/*
branches:
  only:
  - master
  - develop
script:
- npm install
- export ELASTICBEANSTALK_DEPLOYMENT_ZIP_FILE=$TRAVIS_COMMIT_$(date +%Y_%m_%d_%H_%M_%S).zip
- export ELASTIC_BEANSTALK_DESCRIPTION=$TRAVIS_COMMIT_MESSAGE
- export ELASTIC_BEANSTALK_LABEL=$TRAVIS_BRANCH-$TRAVIS_COMMIT
- echo $ELASTIC_BEANSTALK_DESCRIPTION
- echo $ELASTIC_BEANSTALK_LABEL
- zip -r $ELASTICBEANSTALK_DEPLOYMENT_ZIP_FILE . -x .gitignore -q
deploy:
- provider: elasticbeanstalk
  edge: true
  wait_until_deployed: true
  access_key_id: "$AWS_ACCESS_KEY_ID_FOR_DEPLOYMENT"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_FOR_DEPLOYMENT"
  region: ap-southeast-1
  skip_cleanup: true
  zip_file: "$ELASTICBEANSTALK_DEPLOYMENT_ZIP_FILE"
  app: travis-dpl2-eb
  env: TravisDpl2Eb-env
  bucket_name: elasticbeanstalk-ap-southeast-1-468794751428